In [ ]:
from pathlib import Path

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


---

In [ ]:
from pathlib import Path
datafolder = Path('/content/drive/MyDrive/data')
datasets = [i.name for i in datafolder.glob('*') if i.is_file()]
datasets

['movies.txt',
 'addres-book-q.xml',
 'Chinook_Sqlite.sqlite',
 'random.hdf5',
 'titanic.csv',
 'sp500hst.txt',
 'AnnaKarenina_.txt',
 'sp_data2.csv',
 'себестоимостьА_в1.xlsx',
 'data.zip',
 'all_k.zip']

In [ ]:
data_folders = [i.name for i in datafolder.glob('*') if i.is_dir()]
data_folders

['accounts',
 'temperature',
 'recipes_full',
 'reviews_full',
 'reviews_full_mini']

---

Подсчитать, сколько раз встречается каждая из заглавных русских букв в текстовых файлах, лежащих в all_k.zip.
Подсчитать, сколько раз в текстовых файлах, лежащих в all_k.zip, встречаются предложения трех видов: вопросительные (в окончании имеют вопросительный знак), побудительные (в окончании имеют восклицательный знак и не имеют вопросительного) и повествовательные (в окончании имеют точку или троеточие, при этом нужно исключить учет точек, встречающихся в сокращениях, таких как "т.к.").

Подсчитать, сколько раз встречается каждая из заглавных русских букв в текстовых файлах, лежащих в all_k.zip.

---


1)Дан массив A. Построить массив B той же размерности, состоящий из элементов, являющихся суммой минимального элемента массива A по соответствующей строке и минимального элемента A по соответствующему столбцу.Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек.
A=np.array([[ 8, 4, 15, 6, 9], [ 3, 16, 13, 8, 10], [ 0, 9, 18, 17, 5], [16, 2, 6, 0, 10], [18, 13, 9, 17, 8]])"

2) Задать два двухмерных массива ar1 и ar2 размерности (5, 15), состоящих из случайных целых чисел в интервале от -5 до 5. Если значение в ar2 имеет тот же знак, что и соответствующие (по расположению) значение из ar1, то прибавить это значение к соответствующему значению ar1.Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек.

3) Создать двумерный массив 30 на 4, содержащий случайные целые числа от 0 до 100. Интерпретируя массив как 30 векторов из 4х компонент, вернуть массив 5 на 4, состоящий из векторов с наибольшей длиной (евклидовой нормой).Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек.

4) Построить "one-hot encoding" для одномерного массива numpy из целых неотрицательных чисел (длина массива и максимальное значение в массиве заранее неизвестно). Протестировать свое решение на случайно сгенерированном одномерном массиве, соответствующем условию.Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек.


In [ ]:
import numpy as np
A = np.array([[ 8, 4, 15, 6, 9], [ 3, 16, 13, 8, 10], [ 0, 9, 18, 17, 5], [16, 2, 6, 0, 10], [18, 13, 9, 17, 8]])
A

array([[ 8,  4, 15,  6,  9],
       [ 3, 16, 13,  8, 10],
       [ 0,  9, 18, 17,  5],
       [16,  2,  6,  0, 10],
       [18, 13,  9, 17,  8]])

In [ ]:
min = np.min(A , axis = 0)
min_col = np.max(A , axis = 1)
B = np.add(row_min, col_min.reshape(-1,1)).T
B

array([[ 4,  6, 10,  4,  9],
       [ 3,  5,  9,  3,  8],
       [ 0,  2,  6,  0,  5],
       [ 0,  2,  6,  0,  5],
       [ 8, 10, 14,  8, 13]])

In [ ]:
row_min = np.amin(A,axis=1)
col_min = np.amin(A,axis=0)
row_min.shape , col_min.shape

((5,), (5,))

In [ ]:
row_min, col_min

(array([4, 3, 0, 0, 8]), array([0, 2, 6, 0, 5]))

In [ ]:
(np.tile(row_min,(5,1)) + np.tile(col_min,(5,1)).T).T

array([[ 4,  6, 10,  4,  9],
       [ 3,  5,  9,  3,  8],
       [ 0,  2,  6,  0,  5],
       [ 0,  2,  6,  0,  5],
       [ 8, 10, 14,  8, 13]])

---

 Создать двумерный массив 30 на 4, содержащий случайные целые числа от 0 до 100. Интерпретируя массив как 30 векторов из 4х компонент, вернуть массив 5 на 4, состоящий из векторов с наибольшей длиной (евклидовой нормой).Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек.

In [ ]:
matr = np.random.randint(101,size=(30,4))
len_ = np.linalg.norm(matr,axis = 1, ord=2)
top5_ind = np.argsort(len_)[::-1][:5]
matr[top5_ind]

array([[  6,  77, 100,  89],
       [ 66,  88,  20,  98],
       [ 97,  31,  96,  10],
       [ 38,  86,  88,  49],
       [ 52,  70,  96,  41]])

4) Построить "one-hot encoding" для одномерного массива numpy из целых неотрицательных чисел (длина массива и максимальное значение в массиве заранее неизвестно). Протестировать свое решение на случайно сгенерированном одномерном массиве, соответствующем условию.Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек.

In [ ]:
import numpy as np

def one_hot_encoding(arr):
    unique_vals, encoded_arr = np.unique(arr, return_inverse=True)
    encoded = np.eye(len(unique_vals))[encoded_arr]
    return encoded

arr = np.random.randint(0, 1000000, size=10)
encoded_arr = one_hot_encoding(arr)

print("Исходный массив:")
print(arr)
print("\nOne-hot encoding:")
print(encoded_arr)



Исходный массив:
[ 71016 853665 976903 239408 380958 855161 367206  54793 486670 655492]

One-hot encoding:
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
