In [ ]:
from pathlib import Path

---

In [ ]:
from pathlib import Path
datafolder = Path('/content/drive/MyDrive/FinUniver/TOBD_2022/data')
datasets = [i.name for i in datafolder.glob('*') if i.is_file()]
datasets

['AnnaKarenina_.txt',
 'себестоимостьА_в1.xlsx',
 'addres-book-q.xml',
 'all_k.zip',
 'sp500hst.txt',
 'sp_data2.csv',
 'titanic.csv',
 'Chinook_Sqlite.sqlite',
 'data.zip',
 'random.hdf5',
 'movies.txt',
 'addres-book.json',
 'reviews_full.zip',
 'wine.csv.zip',
 'recipes_full.zip',
 'dataset info.gdoc',
 'minutes_n_ingredients_full.hdf5']

In [ ]:
data_folders = [i.name for i in datafolder.glob('*') if i.is_dir()]
data_folders

['accounts',
 'temperature',
 'recipes_full',
 'reviews_full',
 'reviews_full_mini']

In [ ]:
import pandas as pd
def read_csv_from_gdrive(url):
    """
    gets csv data from a given url (taken from file -> share -> copy link)
    :url: example https://drive.google.com/file/d/1BlZfCLLs5A13tbNSJZ1GPkHLWQOnPlE4/view?usp=share_link
    """
    file_id = url.split('/')[-2]
    file_path = 'https://drive.google.com/uc?export=download&id=' + file_id
    data = pd.read_csv(file_path)

    return data


example_link = 'https://drive.google.com/file/d/1BlZfCLLs5A13tbNSJZ1GPkHLWQOnPlE4/view?usp=share_link'
read_csv_from_gdrive(example_link).head(1)

userId  movieId  rating   timestamp
0       1       31     2.5  1260759144

---

# dask.bag
Подсчитать, сколько раз встречается каждая из заглавных русских букв в текстовых файлах, лежащих в all_k.zip.
Подсчитать, сколько раз в текстовых файлах, лежащих в all_k.zip, встречаются предложения трех видов: вопросительные (в окончании имеют вопросительный знак), побудительные (в окончании имеют восклицательный знак и не имеют вопросительного) и повествовательные (в окончании имеют точку или троеточие, при этом нужно исключить учет точек, встречающихся в сокращениях, таких как "т.к.").

Подсчитать, сколько раз встречается каждая из заглавных русских букв в текстовых файлах, лежащих в all_k.zip.

---
# Numpy

1)Дан массив A. Построить массив B той же размерности, состоящий из элементов, являющихся суммой минимального элемента массива A по соответствующей строке и минимального элемента A по соответствующему столбцу.Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек.
A=np.array([[ 8, 4, 15, 6, 9], [ 3, 16, 13, 8, 10], [ 0, 9, 18, 17, 5], [16, 2, 6, 0, 10], [18, 13, 9, 17, 8]])"

2) Задать два двухмерных массива ar1 и ar2 размерности (5, 15), состоящих из случайных целых чисел в интервале от -5 до 5. Если значение в ar2 имеет тот же знак, что и соответствующие (по расположению) значение из ar1, то прибавить это значение к соответствующему значению ar1.Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек.

3) Создать двумерный массив 30 на 4, содержащий случайные целые числа от 0 до 100. Интерпретируя массив как 30 векторов из 4х компонент, вернуть массив 5 на 4, состоящий из векторов с наибольшей длиной (евклидовой нормой).Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек.

4) Построить "one-hot encoding" для одномерного массива numpy из целых неотрицательных чисел (длина массива и максимальное значение в массиве заранее неизвестно). Протестировать свое решение на случайно сгенерированном одномерном массиве, соответствующем условию.Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек.


In [ ]:
import numpy as np
A = np.array([[ 8, 4, 15, 6, 9], [ 3, 16, 13, 8, 10], [ 0, 9, 18, 17, 5], [16, 2, 6, 0, 10], [18, 13, 9, 17, 8]])
A

array([[ 8,  4, 15,  6,  9],
       [ 3, 16, 13,  8, 10],
       [ 0,  9, 18, 17,  5],
       [16,  2,  6,  0, 10],
       [18, 13,  9, 17,  8]])

In [ ]:
min = np.min(A , axis = 0)
min_col = np.max(A , axis = 1)
B = np.add(row_min, col_min.reshape(-1,1)).T
B

array([[ 4,  6, 10,  4,  9],
       [ 3,  5,  9,  3,  8],
       [ 0,  2,  6,  0,  5],
       [ 0,  2,  6,  0,  5],
       [ 8, 10, 14,  8, 13]])

In [ ]:
row_min = np.amin(A,axis=1)
col_min = np.amin(A,axis=0)
row_min.shape , col_min.shape

((5,), (5,))

In [ ]:
row_min, col_min

(array([4, 3, 0, 0, 8]), array([0, 2, 6, 0, 5]))

In [ ]:
(np.tile(row_min,(5,1)) + np.tile(col_min,(5,1)).T).T

array([[ 4,  6, 10,  4,  9],
       [ 3,  5,  9,  3,  8],
       [ 0,  2,  6,  0,  5],
       [ 0,  2,  6,  0,  5],
       [ 8, 10, 14,  8, 13]])

---

 Создать двумерный массив 30 на 4, содержащий случайные целые числа от 0 до 100. Интерпретируя массив как 30 векторов из 4х компонент, вернуть массив 5 на 4, состоящий из векторов с наибольшей длиной (евклидовой нормой).Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек.

In [ ]:
matr = np.random.randint(101,size=(30,4))
len_ = np.linalg.norm(matr,axis = 1, ord=2)
top5_ind = np.argsort(len_)[::-1][:5]
matr[top5_ind]

array([[  6,  77, 100,  89],
       [ 66,  88,  20,  98],
       [ 97,  31,  96,  10],
       [ 38,  86,  88,  49],
       [ 52,  70,  96,  41]])

# 18.05.2023

1) Построить "one-hot encoding" для одномерного массива numpy из целых неотрицательных чисел (длина массива и **максимальное значение в массиве заранее неизвестно**). Протестировать свое решение на случайно сгенерированном одномерном массиве, соответствующем условию.Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек.(```solved```)

---

2)

а) Подсчитать, сколько раз встречается каждая из заглавных русских букв в текстовых файлах, лежащих в all_k.zip. Подсчитать, сколько раз в текстовых файлах, лежащих в all_k.zip, встречаются предложения трех видов: вопросительные (в окончании имеют вопросительный знак), побудительные (в окончании имеют восклицательный знак и не имеют вопросительного) и повествовательные (в окончании имеют точку или троеточие, при этом нужно исключить учет точек, встречающихся в сокращениях, таких как "т.к.").

б) Подсчитать, сколько раз встречается каждая из заглавных русских букв в текстовых файлах, лежащих в all_k.zip. (```todo```)

в) В файлах папки  reviews_full.zip находятся файлы, содержащие информацию об отзывах к рецептам в формате JSON Lines. Отзывы разделены на файлы в зависимости от оценки (например, в файле reviews_1.json находятся отзывы с оценкой 1). Считайте файлы из этого архива в виде dask.bag. Преобразуйте текстовое содержимое файлов в объекты python (с помощью модуля json). Выведите на экран первые 5 элементов полученного bag. Модифицируйте функцию разбора JSON таким образом, чтобы в каждый словарь c информацией об отзыве добавить ключ rating.Рассчитайте среднее значение оценок отзывов с группировкой по месяцам (используйте только методы dask.bag), проверьте результат c использованием dask.dataframe

3) matplotlib

In [ ]:
import numpy as np

In [ ]:
# task
array_size = 3
max_elem = 1_000_000

array = np.random.randint(0, max_elem, array_size)

print(array)

[310650 662920  42758]


In [ ]:
def one(arr):
  """Айдар"""
  u,e = np.unique(arr,return_inverse=True)
  en = np.eye(len(u))[e]
  return en

print(one(array))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
arr = np.array([1,2,3,3,2,1])
unique_count = np.unique(arr).size
one_hot = np.zeros((arr.size, unique_count))
one_hot[np.arange(arr.size), arr-1] = 1
one_hot

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
(размер массива, кол-во уникальных в массиве)

In [ ]:
np.unique(array)

array([0, 4, 5, 7, 8, 9])

In [ ]:
# np.unique(array)

np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# solution
solution_M = None

In [ ]:
# test
m_n_solution_shape = (array_size,array_size)
assert solution_M.shape == m_n_solution_shape, 'wrong shape of sol'

AttributeError: ignored

# 25.05.2023
---

а) Подсчитать, сколько раз встречается каждая из заглавных русских букв в текстовых файлах, лежащих в all_k.zip. Подсчитать, сколько раз в текстовых файлах, лежащих в all_k.zip, встречаются предложения трех видов: вопросительные (в окончании имеют вопросительный знак), побудительные (в окончании имеют восклицательный знак и не имеют вопросительного) и повествовательные (в окончании имеют точку или троеточие, при этом нужно исключить учет точек, встречающихся в сокращениях, таких как "т.к.").(```todo```)

б) Подсчитать, сколько раз встречается каждая из заглавных русских букв в текстовых файлах, лежащих в all_k.zip. (```todo```)

в) В файлах папки  reviews_full.zip находятся файлы, содержащие информацию об отзывах к рецептам в формате JSON Lines. Отзывы разделены на файлы в зависимости от оценки (например, в файле reviews_1.json находятся отзывы с оценкой 1). Считайте файлы из этого архива в виде dask.bag. Преобразуйте текстовое содержимое файлов в объекты python (с помощью модуля json). Выведите на экран первые 5 элементов полученного bag. Модифицируйте функцию разбора JSON таким образом, чтобы в каждый словарь c информацией об отзыве добавить ключ rating.Рассчитайте среднее значение оценок отзывов с группировкой по месяцам (используйте только методы dask.bag), проверьте результат c использованием dask.dataframe.
(```todo```)


1) Датасет: minutes_n_ingredients_full.hdf5 Считайте датасет recipe из файла minutes_n_ingredients_full.hdf5 в виде dask.array. Укажите аргумент chunks=(100_000, 3) при создании массива. Выведите на экран основную информацию о массиве и выберите рецепты, время выполнения которых меньше медианного значения.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import dask.array as da
import h5py
import numpy as np

In [ ]:
path = '/content/drive/MyDrive/minutes_n_ingredients_full.hdf5'

In [ ]:
f = h5py.File(path)
print(list(f.keys()))
data = da.from_array(f['recipe'], chunks=(100_000, 3))

['recipe']


In [ ]:
data

dask.array<array, shape=(2231637, 3), dtype=int64, chunksize=(100000, 3), chunktype=numpy.ndarray>

In [ ]:
median_time = data[:,1:2].mean(axis=0).compute()

selected_recipes = data[data[:, 0] < median_time].compute()

print(selected_recipes)

[[557  80   8]
 [407  25   6]
 [809 150  13]
 ...
 [146 171  11]
 [777   0   8]
 [760   0  10]]


2) Датасет: - Необходимо найти все целые числа от 1 до 400 000, для которых sin от этого числа будет иметь не менее 9 одинаковых цифр (например, sin(139198)=0.30763333543133703; sin(139198)=0.30763333543133703 т.е. имеет 9 троек). Ответ представляет собой список пар (целое число, значение синуса для него), для которых значение синуса удовлетворяет условию. Решение этой задачи распараллелить, используя multiprocessing Pool. Сравнить продолжительность последовательного и параллельного решения задачи.

In [ ]:
import math
from multiprocessing import Pool

def check_sine(n):
    sin_value = math.sin(n)
    sin_str = str(sin_value)
    digit_counts = [sin_str.count(digit) for digit in sin_str if digit.isdigit()]
    if max(digit_counts) >= 9:
        return (n, sin_value)
    return None

def find_numbers_parallel():
    numbers = range(1, 400001)
    with Pool() as pool:
        results = pool.map(check_sine, numbers)
    return [result for result in results if result is not None]

def find_numbers_sequential():
    numbers = range(1, 400001)
    return [check_sine(n) for n in numbers if check_sine(n) is not None]


In [ ]:
%%time
sequential_results = find_numbers_sequential()
print("Sequential results:", sequential_results)

Sequential results: [(1797, 0.009002025051800673), (7089, 0.9999926930119999), (10639, 0.9999937999413936), (24074, 0.024502006300003643), (25904, -0.9999975242999319), (31249, 0.4097000800060077), (36693, -0.7188828881448883), (38968, -0.31007805001001504), (46617, 0.8881880887188651), (47105, -0.04023706000105806), (47306, -0.10200005360030799), (48979, 0.9999999646773939), (50399, 0.9999999894564097), (50754, -0.9999999933794586), (51109, 0.9999999963938254), (51464, -0.9999999984995102), (51819, 0.999999999696513), (52174, -0.9999999999848337), (52529, 0.9999999993644724), (52884, -0.999999997835429), (53239, 0.9999999953977037), (53594, -0.9999999920512962), (54609, 0.9649091969997949), (54659, 0.9999999765599817), (55724, -0.9999999528905291), (58564, -0.9999998497899818), (60694, -0.999999734299931), (63525, 0.9107300260000201), (66374, -0.9999992663984799), (67490, 0.7412811211116511), (78444, -0.9999974997289492), (97284, 0.9917029415999999), (102540, -0.9999099954979505), (10

In [ ]:
%%time
parallel_results = find_numbers_parallel()
print("Parallel results:", parallel_results)

Parallel results: [(1797, 0.009002025051800673), (7089, 0.9999926930119999), (10639, 0.9999937999413936), (24074, 0.024502006300003643), (25904, -0.9999975242999319), (31249, 0.4097000800060077), (36693, -0.7188828881448883), (38968, -0.31007805001001504), (46617, 0.8881880887188651), (47105, -0.04023706000105806), (47306, -0.10200005360030799), (48979, 0.9999999646773939), (50399, 0.9999999894564097), (50754, -0.9999999933794586), (51109, 0.9999999963938254), (51464, -0.9999999984995102), (51819, 0.999999999696513), (52174, -0.9999999999848337), (52529, 0.9999999993644724), (52884, -0.999999997835429), (53239, 0.9999999953977037), (53594, -0.9999999920512962), (54609, 0.9649091969997949), (54659, 0.9999999765599817), (55724, -0.9999999528905291), (58564, -0.9999998497899818), (60694, -0.999999734299931), (63525, 0.9107300260000201), (66374, -0.9999992663984799), (67490, 0.7412811211116511), (78444, -0.9999974997289492), (97284, 0.9917029415999999), (102540, -0.9999099954979505), (1061

3) Датасет: Chinook_Sqlite.sqlite С помощью кода на Python с использованием sqlite3 и SQL решить задачу. Реализовать функции на Python: Которая возвращает всех имеющихся артистов. Которая по имени артиста возвращает все его альбомы с количеством треков в них.

In [ ]:
import sqlite3

conn = sqlite3.connect('/content/drive/MyDrive/Chinook_Sqlite.sqlite')


In [ ]:
def get_all_artists():
    query = "SELECT Name FROM Artist"
    cursor = conn.execute(query)
    artists = [row[0] for row in cursor.fetchall()]
    return artists

In [ ]:
def get_albums_by_artist(artist_name):
    query = """
    SELECT Album.Title, COUNT(Track.TrackId) AS TrackCount
    FROM Artist
    JOIN Album ON Artist.ArtistId = Album.ArtistId
    JOIN Track ON Album.AlbumId = Track.AlbumId
    WHERE Artist.Name = ?
    GROUP BY Album.AlbumId
    """
    cursor = conn.execute(query, (artist_name,))
    albums = cursor.fetchall()
    return albums


In [ ]:
get_all_artists()

['AC/DC',
 'Accept',
 'Aerosmith',
 'Alanis Morissette',
 'Alice In Chains',
 'Antônio Carlos Jobim',
 'Apocalyptica',
 'Audioslave',
 'BackBeat',
 'Billy Cobham',
 'Black Label Society',
 'Black Sabbath',
 'Body Count',
 'Bruce Dickinson',
 'Buddy Guy',
 'Caetano Veloso',
 'Chico Buarque',
 'Chico Science & Nação Zumbi',
 'Cidade Negra',
 'Cláudio Zoli',
 'Various Artists',
 'Led Zeppelin',
 'Frank Zappa & Captain Beefheart',
 'Marcos Valle',
 'Milton Nascimento & Bebeto',
 'Azymuth',
 'Gilberto Gil',
 'João Gilberto',
 'Bebel Gilberto',
 'Jorge Vercilo',
 'Baby Consuelo',
 'Ney Matogrosso',
 'Luiz Melodia',
 'Nando Reis',
 'Pedro Luís & A Parede',
 'O Rappa',
 'Ed Motta',
 'Banda Black Rio',
 'Fernanda Porto',
 'Os Cariocas',
 'Elis Regina',
 'Milton Nascimento',
 'A Cor Do Som',
 'Kid Abelha',
 'Sandra De Sá',
 'Jorge Ben',
 'Hermeto Pascoal',
 'Barão Vermelho',
 'Edson, DJ Marky & DJ Patife Featuring Fernanda Porto',
 'Metallica',
 'Queen',
 'Kiss',
 'Spyro Gyra',
 'Green Day',
 'D

['AC/DC',
 'Accept',
 'Aerosmith',
 'Alanis Morissette',
 'Alice In Chains',
 'Antônio Carlos Jobim',
 'Apocalyptica',
 'Audioslave',
 'BackBeat',
 'Billy Cobham',
 'Black Label Society',
 'Black Sabbath',
 'Body Count',
 'Bruce Dickinson',
 'Buddy Guy',
 'Caetano Veloso',
 'Chico Buarque',
 'Chico Science & Nação Zumbi',
 'Cidade Negra',
 'Cláudio Zoli',
 'Various Artists',
 'Led Zeppelin',
 'Frank Zappa & Captain Beefheart',
 'Marcos Valle',
 'Milton Nascimento & Bebeto',
 'Azymuth',
 'Gilberto Gil',
 'João Gilberto',
 'Bebel Gilberto',
 'Jorge Vercilo',
 'Baby Consuelo',
 'Ney Matogrosso',
 'Luiz Melodia',
 'Nando Reis',
 'Pedro Luís & A Parede',
 'O Rappa',
 'Ed Motta',
 'Banda Black Rio',
 'Fernanda Porto',
 'Os Cariocas',
 'Elis Regina',
 'Milton Nascimento',
 'A Cor Do Som',
 'Kid Abelha',
 'Sandra De Sá',
 'Jorge Ben',
 'Hermeto Pascoal',
 'Barão Vermelho',
 'Edson, DJ Marky & DJ Patife Featuring Fernanda Porto',
 'Metallica',
 'Queen',
 'Kiss',
 'Spyro Gyra',
 'Green Day',
 'D

In [ ]:

artist_name = "AC/DC"
albums = get_albums_by_artist(artist_name)
print(f"Albums by {artist_name}:")
for album in albums:
    print(f"Album: {album[0]}, Track Count: {album[1]}")


Albums by AC/DC:
Album: For Those About To Rock We Salute You, Track Count: 10
Album: Let There Be Rock, Track Count: 8
