# lab1_numpy

data -
[minutes_n_ingredient](https://drive.google.com/file/d/1JGxI5jnfH7KF065xobGmTX_j9TzWV8SU/view?usp=sharing)

сохранить локально или положить на гугл диск

In [ ]:
# не удалять и не изменять код в этой ячейке.

# https://colab.research.google.com/notebooks/io.ipynb#scrollTo=RWSJpsyKqHjH
from google.colab import drive
drive.mount('/content/drive')
# path = "drive/MyDrive/FinUniver/TOBD_2022/sem01_numpy_06-09-2022/data/minutes_n_ingredients.csv"

Mounted at /content/drive


1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

In [ ]:
#<your code here>
import numpy as np
path = "/content/drive/MyDrive/minutes_n_ingredients.csv"
dataset = np.loadtxt(path, delimiter=',', skiprows=1, dtype=np.int32)
dataset[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
#<your code here>
print(np.mean(dataset,0)[1:])
print(np.amin(dataset,0)[1:])
print(np.amax(dataset,0)[1:])
print(np.median(dataset,0)[1:])

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [ ]:
#<your code here>
print(dataset[np.where(dataset[:,1]<(np.quantile(dataset[:,1],0.75)))])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [371794     35      8]
 [ 43407     35      7]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
#<your code here>
print(np.count_nonzero(dataset[:,1]==0))
dataset[:,1]=np.where(dataset[:,1]==0,1,dataset[:,1])
print(np.count_nonzero(dataset[:,1]==0))

479
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
#<your code here>
# print(len(dataset))
print(len(np.unique(dataset, axis=0)))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
#<your code here>
print(len(np.unique(dataset[:,2])))
print((np.unique(dataset[:,2])))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
#<your code here>
dataset5=(dataset[np.where(dataset[:,2]<=5)])
print((dataset5))

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
#<your code here>
a=(dataset)[:,2]/(dataset)[:,1]
print(a)
print(np.amax(a))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
#<your code here>

print(np.mean(dataset[np.argsort(dataset[:, 1])[::-1]][0:100][:,2]))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
#<your code here>
import random
for i in range(10):
  a=random.randint(0,len(dataset))
  print(dataset[a])

[26640    40     9]
[113842    190      9]
[264474     45      8]
[23492    55    16]
[19571    75    10]
[537241     65     21]
[156275     30     11]
[50449    10     8]
[8462   90   10]
[187688      4      3]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
#<your code here>
print(len(dataset[np.where(dataset[:,2]<np.mean(dataset[:,2]))])/len(dataset)*100)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
#<your code here>
ind=np.where((dataset[:,2]<=5) & (dataset[:,1]<=20))
dopcolumn=np.zeros((len(dataset),1),dtype=np.int32)
dopcolumn[ind]=1
datas=np.append(dataset, dopcolumn, axis=1)
print(datas)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:
#<your code here>
print(len(datas[(np.where(datas[:,3]==1))])/len(datas)*100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
#<your code here>
d1=dataset[np.where(dataset[:,1]<10)]
d2=dataset[np.where((dataset[:,1]>=10)&(dataset[:,1]<20))]
d3=dataset[np.where(dataset[:,1]>=20)]
m=min(len(d1),len(d2),len(d3))
dat=np.stack((d1[:m],d2[:m],d3[:m]))
print(dat)
print(dat.shape)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      1      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
(3, 7588, 3)
